[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "PyVMCON"
version = "1.0.0"
description = "python implementation of the VMCON non-linear constrained optimiser."
authors = [{name = "Timothy Nunn", email = "timothy.nunn@ukaea.uk"}]
dependencies = [
    "numpy>=1.19",
    "scipy>=1.6",
    "cvxpy>=1.3"
]

[project.optional-dependencies]
docs = [
    "Sphinx>=6.1.0",
    "sphinx-rtd-theme>=1.2",
]

[tool.setuptools.packages.find]
where = ["src"]
